---

- hosts: all

  tasks:

  - name: ensure apt cache is up to date
    apt: update_cache=yes
    sudo: true

  - name: ensure all packages are up to date
    apt: upgrade=dist
    sudo: true

  - name: ensure that java is installed
    apt: name=openjdk-7-jdk state=present
    sudo: true

  - name: ensure the instance hostname is set to app
    hostname: name=app
    sudo: true

  - name: ensure that the hosts file has the hostname app
    lineinfile: dest=/etc/hosts regexp='^127\.0\.0\.1 localhost' line="127.0.0.1 localhost app"
    sudo: true

  - name: reboot if required
    command: /sbin/reboot removes=/var/run/reboot-required
    sudo: true

  - name: wait for host in case reboot occured
    local_action: wait_for host={{ inventory_hostname }} port=22
