---

- hosts: ci-master

  tasks:
  - name: ensure that the pipeline-user exists
    user: name=pipeline
    sudo: true

  - name: ensure that there is a folder to install the pipeline in
    file: path=/opt/pipeline state=directory owner=pipeline
    sudo: true

  - name: ensure that the initial pipeline is present
    copy: src=../pipeline-0-standalone.jar dest=/opt/pipeline/ owner=pipeline
    sudo: true

  - name: ensure that the the pipeline-start-script is present
    copy: src=../scripts/start-and-restart.sh dest=/opt/pipeline/ mode=755 owner=pipeline
    sudo: true

  - name: ensure that the the pipeline-init-script is present
    copy: src=../scripts/pipeline-init.sh dest=/etc/init.d/pipeline mode=755
    sudo: true

  - name: ensure apt cache is up to date
    apt: update_cache=yes
    sudo: true

  - name: ensure all packages are up to date
    apt: upgrade=dist
    sudo: true

  - name: ensure that java is installed
    apt: name=openjdk-7-jdk state=present
    sudo: true

  - name: ensure that git is installed
    apt: name=git state=present
    sudo: true

  - name: ensure the instance hostname is set to ci-master
    hostname: name=ci-master
    sudo: true

  - name: ensure that the hosts file has the hostname ci-master
    lineinfile: dest=/etc/hosts regexp='^127\.0\.0\.1 localhost' line="127.0.0.1 localhost ci-master"
    sudo: true

  - name: ensure that the leiningen bootstrap script has been downloaded
    get_url: url=https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein dest=/usr/local/bin/lein mode=755
    sudo: true

  - name: ensure that pip is installed
    apt: name=python-pip state=present
    sudo: true

  - name: ensure that the aws cli is installed
    pip: name=awscli
    sudo: true

  - name: ensure that ruby is installed
    apt: name=ruby1.9.1 state=present
    sudo: true

  - name: reboot if required
    command: /sbin/reboot removes=/var/run/reboot-required
    sudo: true

  - name: wait for host in case reboot occured
    local_action: wait_for host={{ inventory_hostname }} port=22

  - name: start pipeline
    service: name=pipeline state=started enabled=true
    sudo: true