---

- hosts: all

  tasks:
  - name: ensure that the pipeline-user exists
    user: name=pipeline
    sudo: true

  - name: ensure that there is a folder to install the pipeline in
    file: path=/opt/pipeline state=directory owner=pipeline
    sudo: true

  - name: ensure that the initial pipeline is present
    copy: src=../pipeline-0-standalone.jar dest=/opt/pipeline/ owner=pipeline
    sudo: true

  - name: ensure that the the pipeline-start-script is present
    copy: src=../scripts/runner.sh dest=/opt/pipeline/ mode=755 owner=pipeline
    sudo: true

  - name: ensure that the the pipeline-init-script is present
    copy: src=../scripts/pipeline-init.sh dest=/etc/init.d/pipeline mode=755
    sudo: true

  - name: restart pipeline
    service: name=pipeline state=restarted enabled=true
    sudo: true